### ISSUE TITLE
Module Checksum Mismatch with GOPRIVATE=*

### ISSUE THREAD

**Issue by rickardgranberg** [go-utils/dedupe#1]
We're using dependabot to manage our module dependencies, and in our specific case, dependabot sets `GOPRIVATE=*` when it runs update checks. This renders the following error:

```
verifying github.com/go-utils/dedupe@v1.0.0/go.mod: checksum mismatch
        downloaded: h1:oRzAt9jnMtYvaAEJDDlRhce1tvDATaUQEszeT/XQxZ0=
        go.sum:     h1:d3isYB4QNtAtaLlVkStDXoq6R0qRAelD48W2VUZUpCg=
````

Normal use (i.e. without setting `GOPRIVATE=*`) works fine.

I'm assuming the v1.0.0 tag was moved in the Git repo after the module was published?
Would it be possible to release a v1.0.1 version to fix this problem?

**Comment by 54m** [comment]
@rickardgranberg Published!
https://github.com/go-utils/dedupe/releases/tag/v1.0.1

**Comment by rickardgranberg** [comment]
That fixed it, many thanks!
